# pytest.ini in the root of your_api_automation_project/

[pytest]
# Always add these command-line options
addopts = -v -s --strict-markers --html=reports/report.html --self-contained-html --log-cli-level=INFO

# Specify directories to search for tests (default is current dir and subdirs)
testpaths = tests

# Define naming conventions for test files, classes, and functions (defaults are often fine)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    prio1: marks tests as priority 1
    prio2: marks tests as priority 2
    prio3: marks tests as priority 3
    smoke: Perform type of test
    regression: Perform type of test

# Control how warnings are handled during test execution
# Example: ignore general deprecation warnings
filterwarnings =
    ignore::DeprecationWarning

# Configure logging for console output during test runs
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Set environment variables for tests (useful for dynamic configuration loading)
#env =
    #API_BASE_URL = https://cnt-4d6b56f4-45ab-4ac1-9073-f600e03f0a09.containerhub.tripleten-services.com/docs/ # <--- REPLACE WITH YOUR ACTUAL BASE URL